### ISSUE TITLE
Request to Update Data Link in README

### ISSUE THREAD

**Issue by Daiqy** [brandonyzhao/rtnf#1]
Hi @brandonyzhao, 

Thank you for your excellent work!

I am trying to access the [data link](https://caltech.box.com/shared/static/lqp8w7mifc4ibbc1fi55v6z8tl4ydi2y.gz) provided in the README. Unfortunately, it seems to have been removed or is no longer accessible. Could you please update the link or give a new way to access the data? Thank you again for your attention to this issue.

Best regards,
Daiqy

**Comment by brandonyzhao** [comment]
Oops, sorry about that. This link should work: 

[new data link](https://caltech.box.com/s/rg5kvbznj6lii52efjjswlda045bz6fr)

Thank you for bringing this to my attention.
